name: main

on:
    push:
        branches:
            - dev

jobs:
    auto-pr:
        name: Automatically test new commits
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Python 3.10
                uses: actions/setup-python@v5
                with:
                    python-version: '3.10'

            -   name: Give execute permissions to scripts
                run: |
                    chmod +x install_dependencies.sh
                    chmod +x generate_report.sh
                    chmod +x show_report.sh

            -   name: Install dependencies
                run: ./install_dependencies.sh

            -   name: Run the code
                run: |
                    source venv/bin/activate
                    ./generate_report.sh
