name: main

on:
    push:
        branches:
            - dev

jobs:
    auto-pr:
        name: Automatically test new commits
        runs-on: ubuntu-latest
        env:
            CI_ENV: true
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Python 3.10
                uses: actions/setup-python@v5
                with:
                    python-version: '3.10'

            -   name: Give execute permissions to scripts
                run: |
                    chmod +x "CLI scripts/Linux/install_dependencies.sh"
                    chmod +x "CLI scripts/Linux/generate_report.sh"
                    chmod +x "CLI scripts/Linux/show_report.sh" 

            -   name: Install dependencies
                run: |
                    cd "CLI scripts/Linux"
                    ./install_dependencies.sh

            -   name: Run the code
                run: |
                    source venv/bin/activate
                    cd "CLI scripts/Linux"
                    ./generate_report.sh
